ZeptrionAirConfig:
  zapp-16510001._zapp._tcp.local.:
    buttons:
      4:
        group: Bad
        name: bad_Lavabo
  zapp-17040075._zapp._tcp.local.:
    buttons:
      2:
        group: new
        name: New_smart_panel_e
      3:
        group: new
        name: New_smart_panel_g
      4:
        group: Stube
        name: stube_Mitte
      6:
        group: Stube
        name: stube_Hinten
  zapp-17040079._zapp._tcp.local.:
    buttons:
      4:
        group: Esszimmer
        name: esszimmer_Esszimmer
  zapp-17040083._zapp._tcp.local.:
    buttons:
      2:
        group: new
        name: New_smart_panel_e
      3:
        group: new
        name: New_smart_panel_g
      4:
        group: Stube
        name: stube_Stube
  zapp-17040087._zapp._tcp.local.:
    buttons:
      2:
        group: new
        name: New_smart_panel_e
      3:
        group: new
        name: New_smart_panel_g
      4:
        group: Stube
        name: stube_vorne
  zapp-17040090._zapp._tcp.local.:
    buttons:
      4:
        group: Kueche
        name: kueche_Kueche
      6:
        group: Kueche
        name: kueche_Sp-Kueche
